#!/bin/bash
DRY=1   # Assume dry, '-run' flag will flip the bit later.
echo "" # Professional padding


# If the script is not outputting to a terminal, don't add colors (good for piping into 'less', among other commands)
# Otherwise, color away.
if [ -t 1 ]
then
  # Some colors
  declare -A colors
  colors[none]="\e[0m"
  colors[red]="\e[31m"
  colors[green]="\e[32m"
  colors[yellow]="\e[33m"
  colors[blue]="\e[34m"
  colors[magenta]="\e[35m"
  colors[cyan]="\e[36m"
  colors[lightgray]="\e[37m"
  colors[white]="\e[97m"
fi

#     _                
#  __| | ___ _ __  ___ 
# / _` |/ _ \ '_ \/ __|
#| (_| |  __/ |_) \__ \
# \__,_|\___| .__/|___/
#           |_|        

for dependency in brctl chrt dhclient dhclient ip qemu-system-x86_64 taskset tr
do
  which $dependency >/dev/null 2>&1 || missing="$missing $dependency "
done
if [[ ! -z "$missing" ]]
then
  echo -ne "Couldn't find these programs:$missing\nPlease install the relevant packages or check your \$PATH."
  exit 1
fi

# _____                 _   _                 
#|  ___|   _ _ __   ___| |_(_) ___  _ __  ___ 
#| |_ | | | | '_ \ / __| __| |/ _ \| '_ \/ __|
#|  _|| |_| | | | | (__| |_| | (_) | | | \__ \
#|_|   \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
# 

function printHelp {
  printer "This script exists to make various vfio activity less convoluted. Among other use-cases"
  printer "such as LiveCD usage, testing if drives boot, PXE imaging, or any thing else with optional PCI passthrough."
  printer "Hopefully somebody finds it useful.\n"

  printer "Valid example arguments: [ ${colors[blue]}There's more in the README.md! ${colors[none]}]\n"

  printer "  ${colors[cyan]}-image /dev/zvol/zpool/windows"
  printer "  ${colors[cyan]}-imageformat/${colors[cyan]}-format [raw / qcow / vdi / etc]"
  printer "    A file or blockdevice to give the guest. Complete with it's [Qemu recognised] format\n"

  printer "  ${colors[cyan]}-iso /path/to/a/diskimage.iso"
  printer "    If you're installing the OS for drivers you may wish to include this\n"

  printer "  ${colors[cyan]}-iommugroups / -iommugrouping"
  printer "    (Try to) Print IOMMU Groups then exit. Useful for the -PCI arg.\n"

  printer "  ${colors[cyan]}-bridge br0,tap0\t${colors[none]}(Attach vm's tap0 to existing br0)"
  printer "  ${colors[cyan]}-bridge br0,tap0,eth0\t${colors[none]}(Create br0, attach vm's tap0 and host's eth0 to br0, use dhclient for a host IP.)"
  printer "    If no network options are specified the default qemu NAT adapter will be used.\n"

  printer "  ${colors[cyan]}-nonet"
  printer "    If specified, the VM is not given a network adapter. Useful if you're passing a USB or PCI network card.\n"

  printer "  ${colors[cyan]}-memory 8192M / ${colors[cyan]}-memory 8G / ${colors[cyan]}-mem xxxxM"
  printer "    Set VM memory (Default is half of system total memory)\n"

  printer "  ${colors[cyan]}-hugepages / ${colors[cyan]}-huge /optional/hugepage/mount"
  printer "    Try to allocate hugepages for qemu with the -mem value specified."
  printer "    If no hugepage mountpoint given as argument, tries /dev/hugepages which is often present."
  printer "    Supports hugepage preallocation from boot time and will use existing pages if free."
  printer "    (May want to specify -mem for this. Half of host ram may be too much.)\n"

  printer "  ${colors[cyan]}-hyperv"
  printer "    Enable hyper-v enlightenments for nested virtualization."
  printer "    Can help invasive anticheats play along however HyperV will need to be enabled in the guest's Features.\n"

  printer "  ${colors[cyan]}-usb 'SteelSeries|Keyboard|Xbox|1234:5678'"
  printer "    A regex for lsusb parsing. Matches against device lines from lsusb output.\n"

  printer "  ${colors[cyan]}-pci 'Realtek|NVIDIA|10ec:8168'"
  printer "    A regex for lspci parsing. Matches against device lines from lspci output.\n"

  printer "  ${colors[cyan]}-looking-glass /  -lookingglass / -lg "
  printer "    Adds a 64MB shared memory module for the Looking Glass project and a spice server onto the guest for input from host during Looking Glass usage.\n"

  printer "  ${colors[cyan]}-extras '-device abc123,b,c,d=e' / -extras '-device AC97' "
  printer "    Accepts a string for arbitrary extra qemu arguments. Highly useful when I want to use extra qemu features without having to implement them into the script right away.\n"

  printer "  ${colors[cyan]}-romfile/-vbios path-to-vbios.bin"
  printer "    Accepts a file path to a rom file to use on any detected GPU during -pci argument processing. You should check the vbios dump you're about to use is safe before using it on a GPU, rom-parser is a good project for this.\n"

  printer "  ${colors[cyan]}-pinvcpus 0,1,2,3,4,5,6${colors[cyan]} / ${colors[cyan]}-pinvcpus 0,2,4,8"
  printer "    A comma delimited list of host threads the Guest's vcpus are allowed to execute on."
  printer "    (Setting this also shapes the guest CPU topology to match.)"
  printer "    If you've configured core isolation on the host, this is the argument for you!\n"

  printer "Please see the README.md file for more information about the flags."
  exit 1
}

function printer {
  echo -e "${@} ${colors[none]}"
}

function permissionsManager { # chown's things before qemu starts, but also tries to return them in the end.
  if isDry ; then return ; fi # Do nothing when dry.

  if ! declare -p Permissions >/dev/null 2>&1 ; then declare -g -A Permissions ; fi # Check array is ready for use.
 
  if [ "$1" == "takeown" ] # Takes ownership of a file or dir with sudo
  then
    for path in "${@:2}"
    do
      originalOwner="$(stat -c %U ${path})"
      if [ "${originalOwner}" == "${USER}" ]
      then
        continue # If we already own this, do nothing.
      else
          # Take ownership but keep track
        Permissions[${path}]=${originalOwner} ; sudo chown ${USER} ${path}
      fi 
    done
  elif [ "$1" == "return" ]
  then
    # Returns all stored in the array to original owner
    for entry in ${!Permissions[@]}
    do
      originalOwner="${Permissions[$entry]}" ; sudo chown ${originalOwner} ${entry}
    done
  fi

}

 # Check if script is in dry mode.
function isDry { if [ $DRY -eq 1 ] ; then return 0 ; else return 1 ; fi ; }

 # Read numeric value from meminfo
function readMeminfo   { if [ ! -z "$1" ]; then grep -m1 "$1" /proc/meminfo | grep -Eo '[0-9]+'; fi ; }
function readHugeInfo  { if [ ! -z "$1" ] && [ ! -z "$2" ]; then cat /sys/kernel/mm/hugepages/hugepages-${1}kB/${2}; fi ; }
function writeHugeInfo { if [ ! -z "$1" ] && [ ! -z "$2" ]; then sudo tee /sys/kernel/mm/hugepages/hugepages-${1}kB/${2} > /dev/null; fi ; }

function gpuCheck { if grep -o '\[VGA controller\]' <<<$(lspci -vnnn -s "$1") > /dev/null 2>&1 ; then return 0 ; else return 1 ; fi }

function bindingTimeout {
  if [ ! -z "$1" ]; then attemptedTask=$1 ; else attemptedTask="bind or unbind" ; fi
  printer "${colors[red]}    The device  $fullBuspath ${colors[red]}// $vendorClass ${colors[red]} Was unable to $attemptedTask after 5 seconds, is something else using it? (E.g This will happen to a GPU in use by X). Giving up."
  exit 1
}

  # Try to undo any mess we've caused at the end of a run
function do_cleanup {
  echo "Cleaning up.."
  permissionsManager return # Restore original permissions if any
  echo -ne ""
  if ! isDry
  then
      # Undo bridge if used
    if [[ ! -z "$bridgeArgs" ]]; then bridger stop $bridgeArgs ; fi
    
  
      # Rebind the console and PCI devices if they were rebound
    if [ ! -z "$pciREGEX" ]
    then
      if [ ! -z "$consoleUnbound" ]; then consoleDrivers bind; fi # var only checked for zero length
      enumeratePCIs restorebind
      if  [ "$dm" == "seen" ]; then echo "Attempting to restore display-manager..." ; sudo systemctl start display-manager ; fi # Start DM if seen before run.
    fi

    if [ ! -z "$HUGEPAGES" ] && [ ! -z "$hugepagesSelfAllocated" ] # Clean up hugepages
    then
      echo 0 | writeHugeInfo ${hugepageSizeKB} nr_hugepages # pack up
    fi
  fi
  [ -f '/dev/shm/looking-glass' ] && rm /dev/shm/looking-glass
  printer "\n${colors[green]}Cleanup complete."
  exit
}

function regexCleanup {
  if [ -z "$@" ] ; then echo "No argument given to regexCleanup" ; return ; fi
  REGEX="$@"
  if grep -qE '^\|' <<< $1; then REGEX=${REGEX#?} ; fi
  if grep -qE '\|$' <<< $1; then REGEX=${REGEX%?} ; fi
  echo $REGEX
}

function bridger {
  # Goal is to attach the vm's tap interface to a bridge. Creates the bridge if missing and attaches host int.
  mode=$1
    br=$2
   tap=$3
   int=$4

  if [ "$mode" == "start" ] && ! isDry
  then
    if [ ! -z "$int" ]
    then
      if [ ! -d /sys/class/net/$int ]      ; then printer "${colors[green]}interface $int specified but not found, not bridging."              ; brStartFault=1 ; exit 1 ; else intExists=1 ; fi
      if [ -L /sys/class/net/$int/master ] ; then printer "${colors[red]}interface $int specified but already part of a bridge, not changing." ; brStartFault=1 ; exit 1 ; fi
    else
      printer "Host int not specified, will attach VM tap to existing bridge"
      intExists=0
    fi

    if [ -L /sys/class/net/$tap ] >/dev/null 2>&1 ; then printer "tap interface $tap already exists (use another name), not bridging." ; brStartFault=1 ; exit 1 ; fi

  if [ ! -z "$int" ]
  then
    intMAC=$(ip link show $int|grep -Po '(?<=ether\ )([a-f]|[0-9]|\:)+')
    tapMAC="52:54:00:$(cut -d':' -f4,5,6 <<<$intMAC)"
  else
    brMAC=$(ip link show $br|grep -Po '(?<=ether\ )([a-f]|[0-9]|\:)+')
    tapMAC="52:54:00:$(cut -d':' -f4,5,6 <<<$brMAC)"
  fi

    if grep -qs -E '^up$' /sys/class/net/$br/operstate
    then
      printer "$br exists and is up, will attach $tap to that."
      bridgePreexists=1
    elif ! grep -qs -E '^up$' /sys/class/net/$br/operstate && [ ! -z "$int" ]
    then
      printer "${colors[green]}bridge $br not found while host int specified, will create $br for this session and attach $int + $tap to it."
      bridgePreexists=0
    else
      printer "${colors[red]}bridge $br not found but no host int specified to bridge VM with. Refusing to create bridge with no host interface."
      brStartFault=1
      exit 1
    fi

    if [ $bridgePreexists -eq 0 ]
    then
      if systemctl is-active NetworkManager >/dev/null ; then sudo systemctl stop NetworkManager ; export nm="seen" ; fi
        # Create the bridge,        bring it up.
      sudo ip link add $br type bridge ; sudo ip link set $br up
        # Remove IPs from int,  attach int to bridge,              give bridge int's mac,                bring int up.
      if [ $intExists = 1 ]
      then
        sudo ip addr flush dev $int && sudo ip link set dev $int master $br && sudo ip link set dev $br address $intMAC ; sudo ip link set $int up ; fi
    fi

      # Always create the tap,          attach tap to bridge,               bring tap up.
    sudo ip tuntap add $tap mode tap && sudo ip link set $tap master $br && sudo ip link set $tap up
    permissionsManager takeown /dev/net/tun
    echo '------------------'
    echo -ne "Bridge details:\n\n" ; brctl show $br ; echo
    if [ $bridgePreexists -eq 0 ] && [ ! -z $int ]
    then
      echo "Running dhclient on $br..."
      sudo dhclient -v $br 2>&1|grep '^DHCPACK'
    else
      printer "${colors[green]}Bridge already existed, not running dhclient -r on it."
    fi
    echo '------------------'
  elif [ "$mode" == "start" ] && isDry
  then
    printer "${colors[green]}-bridge\t\tacknowledged [DRY]"
  elif [ "$mode" == "stop" ] && ! isDry && [ -z "$brStartFault" ]
  then
    if [ $bridgePreexists -eq 0 ]
    then
      printer "${colors[yellow]}Undoing our bridge..."
      dhclient -r $br >/dev/null 2>&1 && printer "${colors[green]}dhcp lease released and dhclient process ended..."
      for i in $tap $br; do sudo ip link set $i down ; sudo ip link del $i; done # Remove the tap and bridge
      if ! ip link show br0 >/dev/null 2>&1; then printer "${colors[green]}Bridge removed."; fi
    else
      printer "${colors[green]}We only attached $tap to an existing bridge this run, removing $tap."
      for i in $tap ; do sudo ip link set $i down ; sudo ip link del $i; done && printer "${colors[green]}$tap removed." # Remove the tap
    fi
    if [ "$nm" == "seen" ]; then sudo systemctl restart NetworkManager ; printer "${colors[green]}NetworkManager restarted." ; fi
  fi


}

function consoleDrivers { # Toggles rendering to Ctrl+Alt+F[0-9]. Needs to be unhooked for GPU passthrough.
  if ! isDry
  then 
    if [[ "$1" -eq 'bind' ]]; then bindBoolean="1"; bindState="$1" ; else bindBoolean="0" ; bindState="unbind" ; fi
    for vtconsole in /sys/class/vtconsole/*; do echo $bindBoolean | sudo tee $vtconsole/bind >/dev/null; done
    echo efi-framebuffer.0 | sudo tee /sys/bus/platform/drivers/efi-framebuffer/$bindState >/dev/null
    consoleUnbound=1
  fi
}

function enumerateUSBs { # This only makes arguments
  echo "USB:"
  lsusbOutput="$(lsusb)"
  usbArgs="-usb"
  USBDevices="$(grep -E "$usbREGEX" <<<"$lsusbOutput")"
  
  while read USBDevice
  do
     vendorProduct="$( grep -Eo '(([0-9]|[a-f]){4}|:){3}' <<<$USBDevice)"
     vendor="$( cut -d':' -f1 <<<"$vendorProduct")"
    product="$( cut -d':' -f2 <<<"$vendorProduct")"
        Name="$(cut -d' ' -f7- <<<"$USBDevice")"
    if [[ ! -z "$vendor" ]] && [[ ! -z "$product" ]]
    then
      newUsbArg="-device usb-host,vendorid=0x$vendor,productid=0x$product"
        usbArgs+=" $newUsbArg"
      printer "  Matched: ${colors[blue]}$vendor:$product '$Name'"
      printer "${colors[green]}    Added to USB Args as:\t$newUsbArg\n"
    else
      printer "${colors[red]}Skipping: '$USBDevice' as there was an issue finding it.\n"
    fi
  done <<<"$USBDevices"
}

function enumeratePCIs { # This makes arguments and also unbinds from drivers. Optional vfio-pci rebinding.
  function gpuDetectedAndInUse {
    printer "${colors[yellow]}    Video device $1 is bound to a driver which isn't vfio-pci and could be in use by the DM, framebuffer or otherwise."
    printer "${colors[yellow]}    For this reason the script will now attempt to stop the display-manager service and unbind "
    printer "${colors[yellow]}    the efi framebuffer instead of risking a driver unbind deadlock in waiting for X to quit."
    printer "${colors[yellow]}    If your X server and virtual consoles don't use this card you can unbind it from its driver manually before running this script."
    if systemctl is-active display-manager >/dev/null && ! isDry
    then
      printer "${colors[yellow]}    Stopping display-manager and unbinding console drivers in 5 seconds..." ; sleep 5
      sudo systemctl stop display-manager ; export dm="seen"
    else
      printer "${colors[yellow]}    Could not find a service for display-manager. Confused but trying to continue anyway."
    fi
    consoleDrivers unbind
  }

  echo "PCI:"
  declare -A -g deviceDrivers # Array for tracking devices and their driver.
  if ! lsmod|grep -q vfio_pci;
  then
    printer "${colors[yellow]}  vfio-pci isn't loaded. Loading it now."
    sudo modprobe vfio-pci
    if [ "$?" -ne "0" ]; then printer "${colors[red]}  Could not modprobe vfio-pci. Please fix this."; exit 1 ; fi
  fi

  lspciOutput="$(lspci -nn)" ; PCIDevices="$(grep -E "$pciREGEX" <<<"$lspciOutput")"
  if [ -z "$PCIDevices" ]; then echo "Couldn't find any PCI devices with regex '$pciREGEX', please try another one. Panicking."; exit 1; fi 
  inc=0
  while read PCIDevice
  do
    shortBuspath="$(cut -d' ' -f1<<<$PCIDevice)"
    fullBuspath="0000:$shortBuspath"
    iommuGroup="$(basename $(readlink /sys/bus/pci/devices/$fullBuspath/iommu_group))"

    printer "  Matched:\t${colors[blue]}$PCIDevice"
    printer "  IOMMU Group:\t${colors[blue]}${iommuGroup}"

    vendorClass="$( grep -Eo '(([0-9]|[a-f]){4}|:){3}' <<<$PCIDevice )"
    vendor="$( cut -d':' -f1 <<<"$vendorClass")"
     class="$( cut -d':' -f2 <<<"$vendorClass")"

    if ! [[ $@ == *"restorebind"* ]] # Do our initial checks unless we're restoring an original driver binding right now
    then
      currentDriver="$(lspci -nn -k -s "$fullBuspath" | grep -oP '(?<=driver in use:\ ).*')"
      if ! [ -z "$currentDriver" ]
      then
        deviceDrivers["$vendorClass"]="$currentDriver" # Add it to the device driver array.
        driver="${deviceDrivers["$vendorClass"]}"
        if [ "$currentDriver" == "vfio-pci" ]
	then
          printer "    [INFO] ${colors[green]}Already bound to $currentDriver, leaving alone."
        else
          printer "    [INFO] ${colors[green]}Detected driver ${driver}${colors[green]} is using this device. It will be re-bound on VM exit."
        fi
      else
        printer "    [INFO] ${colors[green]}Has no driver, it will be bound to vfio-pci and left that way for the remainder of this boot."
      fi
    fi

    driver="${deviceDrivers["$vendorClass"]}"

    if [[ $@ == *"unbind"* ]] && ! isDry
    then
      if ! isDry && gpuCheck $fullBuspath
      then
        if [ ! -z "$driver" ] && [ ! "$driver" == "vfio-pci" ] ; then gpuDetectedAndInUse "$busPath[$vendorClass]" ; fi
      fi
      if [ ! -z "$driver" ] && [ "$driver" != "vfio-pci" ]
      then
        printer "${colors[green]}    Unbinding from:\t${colors[none]}$driver"
	echo "$fullBuspath" | sudo timeout --signal 9 5 tee /sys/bus/pci/devices/$fullBuspath/driver/unbind >/dev/null # Try an unbind but give up after 5 seconds with a kill-9
	if [ $? -eq 137 ]; then bindingTimeout unbind ; exit 1 ; fi

      fi
    elif [[ $@ == *"unbind"* ]] && isDry
    then
      printer "    [DRY]  ${colors[green]}Not unbinding it."
    fi

    if [[ $@ == *"vfiobind"* ]] && ! isDry
    then
        if ! [ "$currentDriver" == "vfio-pci" ]
	then
          printer "${colors[green]}    Adding ID and binding to:\t${colors[none]}vfio-pci"
	  echo "0x$vendor 0x$class" | sudo timeout --signal 9 5 tee /sys/bus/pci/drivers/vfio-pci/new_id >/dev/null 2>&1
          if [ $? -eq 137 ]; then bindingTimeout "bind via new_id" ; exit 1 ; fi
          echo "$fullBuspath" | sudo timeout --signal 9 5 tee /sys/bus/pci/drivers/vfio-pci/bind >/dev/null 2>&1   # Try and bind the PCI address for this device just in case ID already added and not automatically bound
	  if [ $? -eq 137 ]; then bindingTimeout bind ; exit 1 ; fi
        fi
      while ! [ -c /dev/vfio/$iommuGroup ]
      do
        sleep 1 && ((++iommuTimeout))
	if [ $iommuTimeout -gt 5 ]; then printer "${colors[red]}    Timed out waiting for bound device to appear under /dev/vfio" ; exit 1 ; fi
      done
      permissionsManager takeown /dev/vfio/${iommuGroup}
      echo 1 | sudo tee /sys/bus/pci/rescan >/dev/null
    elif [[ $@ == *"vfiobind"* ]] && isDry
    then
      printer "    [DRY]  ${colors[green]}Not binding the device."
      echo
    elif [[ $@ == *"restorebind"* ]] && ! isDry
    then
      if ! [ -z "$driver" ] && [ "$driver" != "vfio-pci" ]
      then
        printer "${colors[green]}    Rebinding $vendorClass back to driver:\t${colors[none]}$driver"
        echo "0x$vendor 0x$class" | sudo tee /sys/bus/pci/drivers/vfio-pci/remove_id >/dev/null &2>&1
	echo "$fullBuspath" | sudo tee /sys/bus/pci/devices/$fullBuspath/driver/unbind       > /dev/null
	echo "$fullBuspath" | sudo tee /sys/bus/pci/drivers/$driver/bind                 > /dev/null
	if [ "$?" -eq "0" ]; then printer "${colors[green]}    Successfully rebound." ; else printer "${colors[red]}    Was unable to rebind it to $driver."; fi
      else
        printer "${colors[green]}    Device $vendorClass had no driver so left bound to vfio-pci."
      fi
    fi


    if gpuCheck $fullBuspath
    then
      printer "${colors[green]}    This appears to be a GPU.\t" && guestGetsGPU=1
      if [ ! -z "$romfilePath" ] && [ -f "$romfilePath" ]
      then
        printer "${colors[green]}    Romfile will be passed to the GPU on VM start.\t"
        pciArgs+=" -device vfio-pci,x-vga=on,multifunction=on,host=$fullBuspath,romfile=$romfilePath,id=hostdev$inc"
      fi
    else
      pciArgs+=" -device vfio-pci,host=$fullBuspath,id=hostdev$inc"
    fi
    ((++inc))
  done <<<"$PCIDevices"
  
  if [[ $var == *"vfiobind"* ]] ; then echo -ne "Here are the completed pciArgs:\n    $pciArgs"; fi
}

function checkVcpuCount {
  for child in /proc/$1/task/* ; do if grep -q CPU $child/comm; then echo $(basename $child) ; fi ; done
}

function pinVcpus {
  if [ -d /proc/$1 ]
  then
      # First, this function will wait for all threads to be accounted for. 
      expectedVcpus=$(echo ${vcpuArray[@]} | wc -w)
      timeout=15 ; timer=0 ; foundVcpus=$(checkVcpuCount $1| wc -l)
      while [ $foundVcpus -lt $expectedVcpus ] && [ $timer -lt $timeout ] 
      do
        foundVcpus=$(checkVcpuCount $1| wc -l)
	((++timer))
	printer "${colors[yellow]}Waiting for vcpus to wake up... $foundVcpus found." >&2
        sleep 1 
      done 
    if [ $timer -eq $timeout ] ; then printer "${colors[red]}The vcpus did not wake up in time. This will happen on large qemu launches or slower systems but pinning failed." >&2 ; fi
      
    threadPinList=$(for child in /proc/$1/task/* ; do if grep -q CPU $child/comm; then echo $(basename $child) ; fi ; done)
    printer "Successfully found $(wc -l <<< $threadPinList) vCPUs on the guest." >&2
    vcpuPosition=0
    while read vcpuPid
    do
      printer "${colors[green]}Pinning vCPU $vcpuPosition to host core ${vcpuArray[$vcpuPosition]}" >&2
      sudo taskset -cp ${vcpuArray[$vcpuPosition]} $vcpuPid >/dev/null # Pin this vcpu to a host thread.
      sudo chrt -p -f 20 $vcpuPid >/dev/null # Use FIFO scheduling on qemu vcpu threads.
      ((++vcpuPosition))

    done <<< "$threadPinList" 
  fi
}


#    _                  
#   / \   _ __ __ _ ___ 
#  / _ \ | '__/ _` / __|
# / ___ \| | | (_| \__ \
#/_/   \_\_|  \__, |___/
#             |___/     

if [[ -z "$@" ]] ; then echo "No args seen. Printing help" ; printHelp ; fi

while [ $# -gt 0 ]
do
  case "$(tr '[:upper:]' '[:lower:]'<<<$1)" in
    -colortest|-colourtest)
       printer "${colors[green]}Ok, printing a color test then exiting..."
       for i in $(sort <<< ${!colors[@]}) ; do printer "Test for: ${colors[$i]}$i " ; done
       echo -ne ""
       exit $?
    ;;
    -nocolor|-nocolors|-nocolor|-nocolors)
       unset colors # Pretty simple color killer.
    ;;
    -iommugroups|-iommugrouping)
      printIOMMU=1
   ;; 
    -bridge)
       bridgeArgs="$(sed 's/,/ /g' <<<$2)"
       shift
    ;;
    -nonet)
       noNet=1
    ;;
     -memory|-mem)
       memoryArgs="$2"
       shift
    ;;
     -huge|-hugepages)
       HUGEPAGES="1"
       if [ -d "$2" ]; then hugePath="$2" ; shift ; fi
    ;;
     -usb)
       usbREGEX="$2"
       shift
    ;;
     -pci)
        pciREGEX="$2"
       shift
    ;;
     -run)
       DRY="0"
    ;;
     -iso)
	isos=(${isos[@]} $2)
        shift
    ;;
     -bios)
        biosPath="$2"
        shift
    ;;
     -pinvcpus)
        vcpuThreads="$2"
        shift
    ;;
     -image)
	declare -A disks
        disks[$2]='' # Declare disk
        latestDisk="$2"
        shift
    ;;
     -imageformat|-format)
	if [ ! -z "$latestDisk" ]; then disks[$latestDisk]="$2" ; fi # Add the format for the most recently declared disk
        shift
    ;;
     -looking-glass|-lookingglass|-lg)
        lookingglass="1"
    ;;
     -extras)
        extras="$2"
        shift
    ;;
     -hyperv)
	hyperv="1"
    ;;
     -romfile|-vbios)
	romfilePath="$2"
	shift
    ;;
     --help|-help)
        printHelp
    ;;
     *) /bin/echo "Unknown argument $1"
        printHelp
    ;;
    esac
    shift
done

# ____                 _____ _ _       _     _   
#|  _ \ _ __ ___      |  ___| (_) __ _| |__ | |_ 
#| |_) | '__/ _ \_____| |_  | | |/ _` | '_ \| __|
#|  __/| | |  __/_____|  _| | | | (_| | | | | |_ 
#|_|   |_|  \___|     |_|   |_|_|\__, |_| |_|\__|
#                                |___/

if [ "$printIOMMU" = "1" ]
then
  printer "${colors[green]}Ok, printing IOMMU Groups then exiting..."
  iommuDir="/sys/kernel/iommu_groups";
  if [ -d $iommuDir ]; then for g in `ls -1v $iommuDir`; do echo "IOMMU Group $g"; for d in $iommuDir/$g/devices/* ; do printer "${colors[cyan]}\t$(lspci -nns ${d##*/})"; done; done ; else echo "Couldn't find $iommuDir" ; fi
  exit $?
fi

if isDry
then
  printer "${colors[magenta]}This is a DRY run. Please specify ${colors[red]}-run${colors[magenta]} to actually run"
else
    # Set a trap to run the cleanup function.
  trap do_cleanup  EXIT HUP INT TERM
fi

  # Check IOMMU is active and grouping things.
if [ -z "$(find /sys/class/iommu/ -type l)" ]; then echo -ne "IOMMU isn't loaded?\n  For an Intel machine you must add 'intel_iommu=on' to your kernel boot options in your bootloader.\n  If you're on an AMD machine instead add these two: 'iommu=pt iommu=1'\n\n  If you've already done this and rebooted, your host may not be compatible or some relevant bios settings could be disabled.\n  Feel free to ask about this in case it's a script fault.\n" ; exit 1; fi

  # Determine Host cpu cores/threads and what the guest gets based on -pinvcpus (if specified).
hostThreads=$(grep -Pom1 'siblings.*\ \K([0-9]+)$' /proc/cpuinfo )
  hostCores=$(grep -Pom1 'cpu cores.*\ \K([0-9]+)$' /proc/cpuinfo)
  if [ "$((hostCores * 2))" == "$hostThreads" ]; then hostIsHT=1; fi #hyperthreading check

if [ -z "$vcpuThreads" ] # vcpu pinning
then
  guestCores=$hostCores ; if [ ! -z $hostIsHT ]; then guestThreads=2; else guestThreads=1; fi
  printer "${colors[yellow]}-pinvcpus\tnot specified, guest will execute on full host CPU without any pinning:\t${colors[none]}($hostCores) with ($hostThreads) threads."
else
  if grep -qE '^([0-9]|,)+$' <<< $vcpuThreads
  then
    printer "${colors[green]}-pinvcpus\tspecified, Guest will run on host CPU threads:${colors[none]}\t$vcpuThreads"
    # Make an array for later reference
    OLDIFS="$IFS" ; IFS=', ' vcpuArray=($(echo $vcpuThreads)) ; IFS="$OLDIFS"
    vcpuCount=$(wc -w <<<${vcpuArray[*]})
      # Check if specified -pinvcpus thread count is divisible by 2. Use hyperthreading/smt if supported
    if (( $vcpuCount % 2 == 0 )) && [ "$hostIsHT" == "1" ] ; then guestCores=$(( vcpuCount / 2 )) ; guestThreads=2; else guestCores=$vcpuCount ; guestThreads=1 ; fi
  vcpuPinningAfterQemuStart=1
  else
    echo "This script's -pinvcpus flag only accepts comma delimited threads at the moment such as: 0,1,2,3,4,5,6, or 0,2,4,8 -- Sorry!"
  fi
fi 

  # Determine guest memory
if [ -z "$memoryArgs" ]
then
  totalHostMemoryKB="$(readMeminfo MemTotal)"
  if [ ! -z "$totalHostMemoryKB" ]
  then
    guestmemoryMB="$((totalHostMemoryKB / 1024 / 2))"
    printer "${colors[yellow]}-memory\t\tnot specified, will use half host total:\t${colors[none]}${guestmemoryMB} MB"
  else
    echo "${colors[red]}Failed to find a default memory value for the guest."
  fi
else
  if  [[ "$memoryArgs" =~ 'G' ]]; then memoryArgs="$(($(grep -Eo '[0-9]+' <<< $memoryArgs) * 1024 ))"; fi # Convert to MB
  guestmemoryMB=$memoryArgs
  printer "${colors[green]}-memory\t\tspecified, guest will receive:\t\t\t${colors[none]}${guestmemoryMB} MB"
fi

  # Eval biosPath
if [[ -z "$biosPath" ]]
then
  defaultBiosPath="/usr/share/ovmf/x64/OVMF_CODE.fd"
  if [[ ! -f "$defaultBiosPath" ]]
  then
    printer "${colors[red]}-bios\t\tnot specified and couldn't find default '$defaultBiosPath'. Please install OVMF or set your .fd file with the -bios argument"
  else
    printer "${colors[green]}-bios\t\tnot specified, using discovered default:\t${colors[none]}${defaultBiosPath}"
    biosPath=$defaultBiosPath
  fi
else
  if [ ! -f "$biosPath" ] ; then printer "${colors[red]}Bios path doesn't appear to exist: ${colors[none]}\t${biosPath}" ; exit 1 ; fi
fi

  # Eval Hugepages
if [  "$HUGEPAGES" == "1" ]
then
  if [ -z "$hugePath" ]
  then
    hugePath="/dev/hugepages" ; hugePathDefault=1
    printer "${colors[yellow]}-hugepages\tspecified for this run but no mountpoint argument specified."
    printer "${colors[yellow]}\t\tAttempting to use kernel default ${colors[none]}${hugePath}."
  else
    printer "${colors[green]}-hugepages\tspecified with custom mountpoint." ; hugePathDefault=0
  fi
  if ! grep "hugetlbfs ${hugePath}" /proc/mounts >/dev/null 2>&1 # Check for a hugetlbfs mount for this path
  then
    printer "${colors[red]}\t\tMountpoint ${colors[none]}${hugePath}${colors[red]} not found in ${colors[none]}/proc/mounts${colors[red]} as type hugetlbfs?"

    if [ "$hugePathDefault" -eq 1 ]
    then
      printer "\t\t${colors[red]}Should typically be mounted by default in Linux. Please try to mount $hugePath"
      printer "\t\t${colors[red]}manually or if you've configured a custom mountpoint please specify it."
    else
      printer "${colors[red]}\t\tIf you don't have a custom hugepage mount such as for"
      printer "${colors[red]}\t\t1GB hugepage preallocation at boot then just use ${colors[none]}-hugepages${colors[red]}"
      printer "${colors[red]}\t\twithout an argument to use the default system hugepages."
    fi
    printer "${colors[red]}\t\tPanicking."
    exit 1
  fi
  hugepageSize="$(grep $hugePath /proc/mounts | grep -Po '(?<=pagesize=).+[A-Z]' | tail -n1)"
  if [[ "$hugepageSize" =~ 'M' ]]
  then
    hugepageSizeMB="$(grep -Eo '[0-9]+' <<< $hugepageSize)"
  elif [[ "$hugepageSize" =~ 'G' ]]
  then
    hugepageSizeMB="(($(grep -Eo '[0-9]+' <<< $hugepageSize) * 1024))"
  else
    printer "${color[red]}\t\tSomething went wrong, I was unable to determine ${hugePath}'s hugepage size via the mountpoint. Panicking." ; exit 1
  fi
  hugepageSizeKB="$((hugepageSizeMB * 1024))"
  printer "${colors[green]}\t\tThe selected hugepage mount's size per page is ${hugepageSizeMB}M"

  pagesRequired="$((guestmemoryMB / hugepageSizeMB))"
  printer "${colors[green]}\t\t${pagesRequired} pages will be deployed for ${guestmemoryMB}MB of VM memory."
  if ! isDry
  then
    if [ $(readHugeInfo ${hugepageSizeKB} free_hugepages) -ge $pagesRequired ]
    then
      printer "\t\t${colors[green]}Hugepages already preallocated with enough free for guest, using those."
    else
      echo 3 | sudo tee /proc/sys/vm/drop_caches >/dev/null && printer "\t\tMemory cache dropped for hugepages..."
      echo -ne "\t\tRunning compact_memory... " ; echo 1 | sudo tee /proc/sys/vm/compact_memory >/dev/null && printer "${colors[green]}OK."
      echo "$pagesRequired" | writeHugeInfo ${hugepageSizeKB} nr_hugepages ; hugepagesSelfAllocated=1
      printer "\t\tGiving hugepages a moment to allocate."
      while [ $(readHugeInfo ${hugepageSizeKB} nr_hugepages) -lt $pagesRequired ]
      do
        echo -ne '.'
        ((++count)) ; if [ $count -gt 30 ]; then break; fi
        sleep 1
      done ; echo '' # Newline
      hugepagesFree="$(readHugeInfo ${hugepageSizeKB} free_hugepages)"
      if [[ "$(readHugeInfo ${hugepageSizeKB} free_hugepages)" -lt "$pagesRequired" ]]
      then
        printer "${colors[red]}Error, couldn't allocate all required pages. Please free up memory or check your system."
        printer "\t${colors[yellow]}(${colors[none]}${hugepagesFree} ${colors[yellow]}pages free out of ${pagesRequired}${colors[yellow]} requested. With that the highest value achieved right now is: -mem $((hugepagesFree * hugepageSizeMB))${colors[yellow]})\n"
        exit 1
      fi
      permissionsManager takeown $hugePath
      printer "\n\n${color[green]}Hugepages ready."
      hugeArgs="-mem-path $hugePath"
    fi
  fi
fi

# Put core QEMU arguments together

  machineArgs="-machine q35,accel=kvm,kernel_irqchip=on" # kernel_irqchip helps prevent PCI Error Code 34 on GPUs.
  cpuArgs="-cpu host,kvm=on,topoext=on"

  if [ ! -z "$hyperv" ]
  then
    printer "${colors[green]}-hyperv\t\tspecified, HyperV Enlightenments will be enabled for this run."
    cpuArgs+=",hv-frequencies,hv-relaxed,hv-reset,hv-runtime,hv-spinlocks=0x1fff,hv-stimer,hv-synic,hv-time,hv-vapic,hv-vpindex"
  fi

  smpArgs="-smp sockets=1,cores=$guestCores,threads=$guestThreads"
  coreArgs="$machineArgs -enable-kvm -m $guestmemoryMB $cpuArgs $smpArgs"
  coreArgs+=" -name $(basename $0),debug-threads=on"
  coreArgs+=" -drive if=pflash,format=raw,unit=0,readonly=on,file=$biosPath"
  coreArgs+=" -serial mon:stdio" # Add a qemu serial device
  coreArgs+=" -nodefaults"       # Don't use any default devices
if [[ ! -z "${!disks[@]}" ]]
then
  printer "${colors[green]}-image(s)\tspecified, using disks this run:"
else
  printer "${colors[yellow]}-image\t\tnot specified, This VM will run diskless."
fi

for disk in ${!disks[@]}
do
  ((++ioCounter))
  if [ ! -z "${disks[$disk]}" ]; then diskFormat=",format=${disks[$disk]}"; else unset diskFormat ; fi
  printer "\t\t${ioCounter}\n\t\t  ${colors[blue]}Path:\t\t${colors[none]}${disk}\n\t\t${colors[blue]}  Format:\t${colors[none]}${disks[$disk]}"
  permissionsManager takeown ${disk}
  coreArgs+=" -drive file=$disk,if=none,discard=on,id=drive${ioCounter}${diskFormat} -device virtio-blk-pci,drive=drive${ioCounter},id=virtio${ioCounter},iothread=iothread${ioCounter} -object iothread,id=iothread${ioCounter}"
done

if [ ! -z "$isos" ]
then
  printer "${colors[green]}-iso(s)\tattached:"
  for iso in ${isos[@]}
  do
    ((++ioCounter))
    printer "\t\t${ioCounter}\t${colors[blue]}\n\t\t  Path:\t\t${colors[none]}${iso}"
    coreArgs+=" -drive file=${iso},index=${ioCounter},media=cdrom"
  done
fi


if [ ! -z "$romfilePath" ]
then
  printer "${colors[green]}-romfile\tspecified, if a GPU is detected in the -pci arguments this romfile will be used."
  printer "\t\t$romfilePath"
  if [ ! -f "$romfilePath" ] ;then printer "${colors[red]}\t\tBut the romfile doesn't appear to exist? Panicking" ; exit 1 ; fi
  printer "\t\t${colors[yellow]}Please confirm your romfile is safe with a project such as rom-parser before using this feature"
  sleep 3
fi

if [ ! -z "$lookingglass" ]
then
  printer "${colors[green]}-lookingglass\tspecified, we'll start qemu with a spice server and shared memory for it."
  # Bad way to do this but wanted to keep them readable individually
  lgArgs+=" -object {'qom-type':'memory-backend-file','id':'lgMemory0','mem-path':'/dev/shm/looking-glass','size':67108864,'share':true}" # Memory currently hardcoded to 64M, can be changed in this script if needed. Plan to take resolution as an argument in future.
  lgArgs+=" -device ivshmem-plain,id=shmem0,memdev=lgMemory0,id=lookingglass"
  lgArgs+=" -chardev spicevmc,id=charchannel0,name=vdagent"
  lgArgs+=" -device virtio-serial"
  lgArgs+=" -chardev socket,path=/dev/shm/vmsocket,server=on,wait=off,id=vmsocket"
  lgArgs+=" -device virtserialport,nr=1,chardev=charchannel0,id=channel0,name=com.redhat.spice.0"
  lgArgs+=" -audiodev id=audio1,driver=spice"
  lgArgs+=" -spice port=5900,addr=127.0.0.1,disable-ticketing=on,image-compression=off,seamless-migration=on"
  lgArgs+=" -chardev spicevmc,id=charredir0,name=usbredir"
  lgArgs+=" -chardev spicevmc,id=charredir1,name=usbredir" 
fi

if [ ! -z "$extras" ]
then
  printer "${colors[green]}-extras\t\tspecified, we'll start qemu with these extra arguments:${colors[none]}\t$extras"
  echo '' # spacer
fi


if [[ ! -z "$bridgeArgs" ]];
then
  # Make the bridge
  bridger start $bridgeArgs
  networkArgs="-netdev tap,id=vmnet,ifname=$tap,script=no,downscript=no" # Bridge
  printer "${colors[green]}-bridge\t\tspecified, VM will be bridged to the host with a tap adapter."
elif [[ ! -z "$noNet" ]]
then
  networkArgs="-nic none"
  printer "${colors[green]}-nonet\t\tspecified, there will be no virtual network for the VM this run."
else
  networkArgs+=" -netdev user,id=vmnet" # NAT
  printer "${colors[yellow]}-bridge/-nonet\tnot specified, VM will be given a NAT adapter\n\t\twith a random mac suffix (guest to host) this run.\n\t\tOK for most applications."
fi

 # If tapMAC unset (e.g. nat/user-mode guestnetworking), generate a random one for the run.
if [ -z "$tapMAC" ]; then tapMAC="52:54:00:$(openssl rand -hex 3 | sed 's/.\{2\}/&:/g;s/:$//')" ; fi 

networkArgs+=" -device virtio-net,netdev=vmnet,mac=$tapMAC"

  # Remove any leading/trailing pipes from the regex just in case.
if [ ! -z "$usbREGEX" ]; then usbREGEX=$(regexCleanup "$usbREGEX") ; fi
if [ ! -z "$pciREGEX" ]; then pciREGEX=$(regexCleanup "$pciREGEX") ; fi

if [ ! -z "$usbREGEX" ]; then enumerateUSBs ; fi
if [ ! -z "$pciREGEX" ]; then enumeratePCIs unbind vfiobind ; fi


  # Must do this after enumerating a PCI regex as it checks for GPUs first.
  # Create a display spicey display only if
  # 1. The guest gets no PCI GPU 
  # 2. $DISPLAY is set.

if [ -z "$guestGetsGPU" ] && [[ ! -z "$DISPLAY" ]]
then
  printer  "${colors[green]}Guest has no GPU but \$DISPLAY variable is set [$DISPLAY]. Giving it a virtual screen for this run."
  coreArgs+=" -display sdl -vga virtio" # Create X11 window if no passthrough used. Also if $DISPLAY isn't set.
elif [ ! -z "$guestGetsGPU" ]
then
  printer  "${colors[green]}Guest will get a PCI gpu, no virtual monitor will be attached."
  coreArgs+=" -nographic -vga none"
elif [ -z "$DISPLAY" ]
then
  printer  "${colors[green]}DISPLAY variable unset, guest will have no graphics this session."
  coreArgs+=" -nographic -vga none"
fi 


# _____ _
#|  ___| |_   _
#| |_  | | | | |
#|  _| | | |_| |
#|_|   |_|\__, |
#         |___/

if isDry;
then
  echo "---------------------"
  echo "Here are the completed args from this DRY run:"
  printer "Core:\n${colors[blue]} $coreArgs $hugeArgs"
  if [ ! -z "$networkArgs" ]; then printer "Net :\n${colors[blue]}${networkArgs}"     ; fi
  if [ ! -z "$usbArgs" ] ;    then printer "USB :\n${colors[blue]}${usbArgs}"         ; fi
  if [ ! -z "$pciArgs" ] ;    then printer "PCI :\n${colors[blue]}${pciArgs}"         ; fi
  if [ ! -z "$lgArgs" ] ;     then printer "Looking Glass:\n${colors[blue]}${lgArgs}" ; fi
  if [ ! -z "$extras" ] ;     then printer "Extras:\n${colors[blue]}${extras}"        ; fi
  echo -ne "\nRun the script with the same arguments again and include ${colors[red]}-run${colors[none]} to actually pass these to qemu-system-x86_64\n"
  exit 0
else
  sudo prlimit --pid $$ --memlock=unlimited:unlimited
  set -m # Allow scripted bash job controls (fg, bg, etc)
  echo -ne "Starting qemu now.\n\n"
  qemu-system-x86_64 $coreArgs $hugeArgs $networkArgs $usbArgs $pciArgs $lgArgs $extras &
  sudo chrt -p 1 -p $! >/dev/null                  # Set qemus threads to have high priority
  if [ ! -z $vcpuPinningAfterQemuStart ]; then pinVcpus $! & sleep 1 ; fi
  fg # Bring qemu console into foreground
fi


#Cleanup will catch on Exit
